# -*- coding: utf-8 -*-
"""Trabajo_Mogo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A9B5dwjZRJtOfjqOvAVEQFdDDYcIjytV

#**Presentación del Proyecto**

<font size="+3" face="Verdana" color="green">***Universidad de Córdoba***</font>

<font size="+2" face="Verdana" color="greenyello">***ING SISTEMAS***</font>

<br>

<font size="+1" face="Verdana" color="black">**Proyecto:**</font> *Employee Attrition*

<font size="+1" face="Verdana" color="Black">**Creador:**</font> *Cristian David Miranda Garces*

<font size="+1" face="Verdana" color="Black">**Dataset:**</font> *https://www.kaggle.com/datasets/patelprashant/employee-attrition*

<font size="+1" face="Verdana" color="black">**Fecha:**</font> *9/9/24*


<br>
<br>

<font size="+1" face="Verdana" color="gray">***Link Descarga Dataset:***</font>
https://mega.nz/file/gIgUBCxY#civtblEZoQpi9DPlurb4CAaHEV3rQjq0DPh5Lw2ngus
<br>
<br>

##**Descripcion del proyecto**

**Contexto:**<br> Conjunto de datos ficticios sobre la pérdida y el rendimiento de los empleados de RR.HH.   
<br>

**Objetivo:** <br>
La clave del éxito en cualquier organización es atraer y retener a los mejores talentos. Soy analista de RR.HH. en mi empresa y una de mis tareas es determinar qué factores mantienen a los empleados en mi empresa y cuáles hacen que otros se vayan.

##**Biblioteca de paquetes necesarios**
"""

# Instalar el paquetes necesarios
install.packages("MASS")
install.packages("ISLR")
install.packages("dplyr")
install.packages("ggplot2")
install.packages("readr")
install.packages("tidyverse")
install.packages("cluster")
install.packages("naniar")

# Cargar el paquete MASS
library(MASS)
library(ISLR)
library(dplyr)
library(ggplot2)
library(readr)
library(tidyverse)
library(cluster)
library(naniar)

"""###**Cargar CSV**"""

# Cargar el archivo CSV
df <- read.csv("Employee attrition.csv")

"""###**Diccionario de datos**

**Nombre | Descripción <br> ----------|-----------** <br>

**Age**  | Edad del Empleado <br>

**Attrition** | Empleado que deja la empresa - (0=no,1=sí) <br>

**Business Travel** | Nivel de viaje del empleado - (1=Sin Viajes, 2=Viaja Frecuentemente, 3=Viaja Raramente) <br>

**Daily Rate** | Nivel salarial del empleado <br>

**Department** | Departamento del Empleado - (1=RRHH, 2=I+D, 3=Ventas) <br>

**Distance From Home** | Distancia de la casa al trabajo <br>

**Education** | Nivel educativo del empleado - (1=Menos de Colegio, 2= Colegio, 3= Licenciatura, 4= Máster, 5= Doctorado) <br>

**Education Field** | Campo de educación del empleado - (1=RRHH, 2=Ciencias de la Vida, 3=Marketing, 4=Ciencias Médicas, 5=Otros, 6=Técnico) <br>

**Employee Count** | Número de Empleados <br>

**Employee Number** | ID del Empleado <br>

**Environment Satisfaction** | Satisfacción con el ambiente - (1=Baja, 2=Media, 3=Alta, 4=Muy Alta) <br>

**Gender** | Género del Empleado - (1=FEMENINO, 2=MASCULINO) <br>

**HourlyRate** | Salario por hora del empleado <br>

**Job Involvement** | Participación en el trabajo - (1=Baja, 2=Media, 3=Alta, 4=Muy Alta) <br>

**Job Level** | Nivel del trabajo del empleado <br>

**Job Role** | Rol del Empleado - (1=REP. RRHH, 2=RRHH, 3=TÉCNICO DE LABORATORIO, 4=GERENTE, 5=DIRECTOR GENERAL, 6=DIRECTOR DE INVESTIGACIÓN, 7=CIENTÍFICO DE INVESTIGACIÓN, 8=EJECUTIVO DE VENTAS, 9=REPRESENTANTE DE VENTAS) <br>

**Job Satisfaction** | Satisfacción con el trabajo del empleado - (1=Baja, 2=Media, 3=Alta, 4=Muy Alta) <br>

**Martial Status** | Estado civil del empleado - (1=Divorciado, 2=Casado, 3=Soltero) <br>

**Monthly Rate** | Salario mensual del empleado <br>

**NumCompaniesWorked** | Número de empresas en las que ha trabajado <br>

**Over 18** | ¿El empleado tiene más de 18 años? (1=Sí, 2=No) <br>

**Overtime** | ¿El empleado trabaja horas extra? (1=No, 2=Sí) <br>

**Percent Salary Hike** | Incremento porcentual del salario del empleado <br>

**Performance Rating** | Calificación del rendimiento del empleado - (1=Baja, 2=Buena, 3=Excelente, 4=Excepcional) <br>

**Relations Satisfaction** | Satisfacción con las relaciones del empleado - (1=Baja, 2=Media, 3=Alta, 4=Muy Alta) <br>

**Standard Hours** | Horario estándar del empleado <br>

**Stock Options Level** | Nivel de opciones de acciones del empleado <br>

**Total Working Years** | Total de años trabajados por el empleado <br>

**Training Times Last Year** | Horas de capacitación del empleado <br>

**Work Life Balance** | Equilibrio entre trabajo y vida del empleado - (1=Malo, 2=Bueno, 3=Mejor, 4=Excelente) <br>

**Years at company** | Número total de años en la empresa del empleado <br>

**Years in Current Role** | Número de años en el rol actual del empleado <br>

**Years since Last Promotion** | Número de años desde la última promoción <br>

**Years with Current Manager** | Número de años con el gerente actual

##**Verificación del DataFrame**

###**Observación del dataset**
"""

class(df)

head(df)

"""###**Verificación la estructura de datos**"""

# Verificar la estructura actual del dataset
print(df)

"""###**Verificación de tipo de datos**"""

glimpse(df)

"""##**Cuestionario**

###**1. Distribución de la variable objetivo(Attrition):**

- ¿Cuál es el porcentaje de empleados que han abandonado la empresa?
"""

# Distribución de la variable objetivo
abandono_porcentaje <- df %>%
  group_by(Attrition) %>%
  summarise(count = n()) %>%
  mutate(percentage = count / sum(count) * 100)

print(abandono_porcentaje)

"""**83.9%** de los empleados no han abandonado la empresa.
<Br>

**16.1%** de los empleados sí han abandonado la empresa.

- ¿Existen diferencias significativas en la tasa de abandono entre diferentes
departamentos o áreas de la empresa?
"""

# Tasa de abandono por departamento
abandono_departamento <- df %>%
  group_by(Department, Attrition) %>%
  summarise(count = n()) %>%
  mutate(percentage = count / sum(count) * 100)

print(abandono_departamento)

"""**Distribución de la tasa de abandono por departamento:**

<Br>

**En Human Resources** (Recursos Humanos):

**81%** de los empleados no han abandonado la empresa.

**19%** de los empleados han abandonado la empresa.

<Br>

**En Research & Development** (Investigación y Desarrollo):

**86.2%** de los empleados no han abandonado la empresa.

**13.8%** de los empleados han abandonado la empresa.


<Br>

**En Sales** (Ventas):

**79.4%** de los empleados no han abandonado la empresa.

**20.6%** de los empleados han abandonado la empresa.

###**2. Análisis univariado de las variables numéricas:**

- ¿Cuál es la distribución de los salarios? ¿Existen valores atípicos?
"""

# Distribución de los salarios
summary(df$MonthlyIncome)

# Boxplot para detectar valores atípicos
boxplot(df$MonthlyIncome, main = "Distribución de Salarios")

"""**Interpretación:**
<br>

Podemos notar que los ingresos mensuales varían desde 1009 hasta 19999, con un ingreso medio de 6503 unidades monetarias.

- ¿Cómo se distribuye la antigüedad en la empresa? ¿Hay una relación entre la
antigüedad y el abandono?
"""

# Distribución de la antigüedad
summary(df$YearsAtCompany)

# Relación entre antigüedad y abandono
abandono_antiguedad <- df %>%
  group_by(Attrition) %>%
  summarise(media_antiguedad = mean(YearsAtCompany, na.rm = TRUE))

print(abandono_antiguedad)

# Boxplot para detectar valores atípicos
boxplot(df$YearsAtCompany, main = "Distribución de antigüedad(años)")

"""**Distribución antigüedad** <br>
Mínima: 0 años <br>
Promedió: 7 años <br>
Máximo: 40 años <br>

**Relación entre antigüedad y abandono:** <br>

- Los empleados que no abandonaron tienen una media de antigüedad de 7.37 años. <Br>

- Los empleados que abandonaron tienen una media de antigüedad de 5.13 años.

- ¿Cuál es la distancia promedio de casa al trabajo y cómo se relaciona con el
abandono?
"""

# Distancia promedio casa-trabajo
summary(df$DistanceFromHome)

# Relación entre distancia y abandono
abandono_distancia <- df %>%
  group_by(Attrition) %>%
  summarise(media_distancia = mean(DistanceFromHome, na.rm = TRUE))

print(abandono_distancia)

# Boxplot para detectar valores atípicos
boxplot(df$DistanceFromHome, main = "Distribución de Distancia(km)")

"""**Distribución distancia**

La distancia mínima: 1km<br>
Median: 7km<br>
Promedió: 9km<br>
La distancia más larga: 29k

<br>

**Relación entre distancia y abandono:**
<br>
- Los empleados que no abandonaron viven, en promedio, a 8.92 km del trabajo.
<br>

- Los empleados que abandonaron viven, en promedio, a 10.6 km del trabajo.

###**3. Análisis univariado de las variables categóricas:**

- ¿Cuál es la distribución de los empleados por género, estado civil y nivel
educativo?
"""

# Distribución de Género, Estado Civil y Nivel Educativo
cat("Distribución de Género:\n")
print(table(df$Gender))
cat("\n")

cat("Distribución de Estado Civil:\n")
print(table(df$MaritalStatus))
cat("\n")

cat("Distribución de Nivel Educativo:\n")
print(table(df$EducationField))
cat("\n")

"""- ¿Existe alguna relación entre el nivel de satisfacción en la empresa y el
abandono?
"""

# Relación entre satisfacción y abandono
abandono_satisfaccion <- df %>%
  group_by(Attrition) %>%
  summarise(media_satisfaccion = mean(JobSatisfaction, na.rm = TRUE))

print(abandono_satisfaccion)

#gráfica
ggplot(abandono_satisfaccion, aes(x = Attrition, y = media_satisfaccion, fill = Attrition)) +
  geom_bar(stat = "identity") +
  labs(title = "Satisfacción Media por Estado de Abandono",
       x = "Estado de Abandono",
       y = "Satisfacción Media (Escala 1-5)",
       fill = "Abandono") +
  theme_minimal()

"""**Interpretación:** <br>
La satisfacción es de 1-5

- Los empleados que no han abandonado la empresa tienen una media de satisfacción laboral de 2.78.

- Los empleados que han abandonado la empresa tienen una media de satisfacción laboral de 2.47

- ¿Cómo se distribuyen los empleados en cuanto a si realizan horas extras?
"""

# Distribución de empleados que realicen horas extras
table(df$OverTime)

#grafica

hora_extra_distribution <- df %>%
  count(OverTime)

# Crear la gráfica
ggplot(hora_extra_distribution, aes(x = OverTime, y = n, fill = OverTime)) +
  geom_bar(stat = "identity") +
  labs(title = "Distribución de Empleados que Realizan Horas Extras",
       x = "Horas Extras",
       y = "Número de Empleados",
       fill = "Horas Extras") +
  theme_minimal()

"""###**4. Análisis bivariado:**

- ¿Existe una correlación entre el salario y la antigüedad en la empresa?
"""

# Correlación entre salario y antigüedad
cor(df$MonthlyIncome, df$YearsAtCompany, use = "complete.obs")

"""**Interpretación:**

El valor de 0.514 indica una correlación moderada. También a medida que aumenta la antigüedad en la empresa, también tiende a aumentar el salario mensual.

- ¿Los empleados con mayor antigüedad tienen menos probabilidades de
abandonar?
"""

# Antigüedad para empleados que han abandonado la empresa
cat("Resumen de la Antigüedad - Empleados que Abandonaron:\n")
print(summary(df$YearsAtCompany[df$Attrition == "Yes"]))
cat("\n")

# Antigüedad para empleados que no han abandonado la empresa
cat("Resumen de la Antigüedad - Empleados que No Abandonaron:\n")
print(summary(df$YearsAtCompany[df$Attrition == "No"]))
cat("\n")

"""**Interpretación**
<Br>

**Empleados que Abandonaron:**

Mediana: 3 años

Media: 5.13 años

Máximo: 40 años


**Empleados que No Abandonaron:**

Mediana: 6 años

Media: 7.37 años

Máximo: 37 años

<Br>
Con base a los resultados, sí parece que los empleados con mayor antigüedad tienen menos probabilidades de abandonar

- ¿Hay diferencias en la tasa de abandono entre diferentes rangos salariales?
"""

# Agrupación por rangos salariales y abandono
df <- df %>%
  mutate(SalaryRange = cut(MonthlyIncome, breaks = 4))

abandono_salario <- df %>%
  group_by(SalaryRange, Attrition) %>%
  summarise(count = n()) %>%
  mutate(percentage = count / sum(count) * 100)

print(abandono_salario)

"""**Interpretación:**
Nos enfocamos solo en los que abandonaron(NO) y aplicamos 4 rangos de salarios

**Repuesta:**
Sí, hay diferencias claras en la tasa de abandono entre los diferentes rangos salariales:

- Rango salarial más bajo (990 - 5,760): Tiene la tasa de abandono más alta, con un 19.7% de empleados abandonando.

- Rango medio-bajo (5,760 - 10,500): La tasa de abandono disminuye a 14.2%.

- Rango medio-alto (10,500 - 15,300): La tasa de abandono baja aún más, al 8.7%.

- Rango salarial más alto (15,300 - 20,000): La tasa de abandono es la más baja, con solo un 3.79% de empleados abandonando.

- ¿Existe una relación entre el nivel educativo y el rango salarial?
"""

# Relación entre nivel educativo y rango salarial
salario_educacion <- df %>%
  group_by(Education) %>%
  summarise(media_salario = mean(MonthlyIncome, na.rm = TRUE), .groups = 'drop')

# Imprimir el resumen
print(salario_educacion)

"""**Recordemos:**

Nivel de educación del empleado:

1 = Inferior a la universidad <br>
2 = Universidad<br>
3 = Licenciatura<br>
4 = Maestría <br>
5 = Doctor
"""

#gráfica
ggplot(salario_educacion, aes(x = Education, y = media_salario, fill = Education)) +
  geom_bar(stat = "identity") +
  labs(title = "Salario Promedio por Nivel Educativo",
       x = "Nivel Educativo",
       y = "Salario Promedio") +
  theme_minimal()

"""**Respuesta:** <br>
Podemos notar entre más alto sea el nivel educativo, mejor será el salario... Así que si existen dicha tendencia.

- ¿Los empleados que viven más lejos tienen más probabilidades de abandonar?
"""

# Relación entre distancia y abandono
cor(df$DistanceFromHome, df$Attrition == "Yes", use = "complete.obs")

"""**Interpretación:**
La correlación de 0.078 indica que hay una relación muy débil entre la distancia desde el hogar y el abandono.

Y esto lo podemos comprobar mediantes las respuestas obtenidas en la pregunta
 **"¿Cuál es la distancia promedio de casa al trabajo y cómo se relaciona con el abandono?"**

<Br>
Dónde:

- Los empleados que no abandonaron viven, en promedio, a 8.92 km del trabajo.

- Los empleados que abandonaron viven, en promedio, a 10.6 km del trabajo.

Notamos que existe una mayor tendencia de abandono en base a una mayor distancia desde el hogar, pero no es muy significativa con respeto a una distancia menor

###**5. Análisis de grupos:**

- ¿Podemos identificar grupos de empleados con características similares en cuanto
a su probabilidad de abandono? (Por ejemplo, utilizando técnicas de clustering)

**Clustering**

**Variables a utilizar:** <br>
Utilizaremos las variables numéricas más relevantes y que hemos trabajo anteriormente.
- satisfacción laboral
- antigüedad
- distancia al trabajo
- Ingreso Mensual

**Aplicación de técnicas de clustering (K-means):**


Dividiremos los 1470 datos en tres grupos
"""

# Convertir Attrition a numérico (1 para "Yes", 0 para "No")
df$Attrition <- ifelse(df$Attrition == "Yes", 1, 0)

# Seleccionar las variables relevantes
df_clustering <- df %>%
  select(JobSatisfaction, YearsAtCompany, MonthlyIncome, DistanceFromHome, Attrition)

# Escalar las variables
df_scaled <- scale(df_clustering %>% select(-Attrition))

# Aplicar K-means clustering con 3 clusters (ajustar según necesidad)
set.seed(123)
kmeans_result <- kmeans(df_scaled, centers = 3)

# Agregar los clusters al dataset original
df$Cluster <- as.factor(kmeans_result$cluster)

# Ver la distribución de abandono dentro de los clusters
table(df$Cluster, df$Attrition)

"""**Clúster + Probabilidad de abandono**"""

cluster_summary <- df %>%
  group_by(Cluster) %>%
  summarise(
    count = n(),
    count_abandon = sum(Attrition == 1),
    percentage_abandon = (sum(Attrition == 1) / n()) * 100
  )

print(cluster_summary)

"""**Interpretación:**  <br>
Porcentaje de abandono <Br>
- Grupo 1 = 16%
- Grupo 2 = 22%
- Grupo 3 = 7%

**Conclusión:**
Podemos notar que el grupo #1 a pesar de tener 895 empleados con características similares, no es quien sufre más abandonó... Se podría decir que dicho  grupo tiene más margen de fidelidad con la empresa. Y se podría seguir trabajando con este grupo para llegar a conclusión mas acertadas.

**Gráfica de distribución de grupos**
Empleados con características similares en base a antigüedad y ingreso mensual
"""

ggplot(df, aes(x = YearsAtCompany, y = MonthlyIncome, color = Cluster)) +
  geom_point() +
  labs(title = "Clustering de empleados basado en antigüedad y ingreso mensual")

"""- ¿Existen diferencias significativas en los perfiles de los empleados que se quedan
y los que se van?
"""

df %>%
  group_by(Cluster, Attrition) %>%
  summarise(
    mean_income = mean(MonthlyIncome),
    mean_satisfaction = mean(JobSatisfaction),
    mean_years = mean(YearsAtCompany),
    count = n()
  )

"""**Recordar** <br>
Attrition <br>
1 = yes <br>
0 = No <br>


**Interpretación:** <br>
- Podemos notar que el promedio del salario mensual es mayor para quienes se quedan, y esto sucede en los 3 grupos.
- En los 3 grupos, los que abandonan registran un salario menor.
- Salvó en el grupo 3 los que no se quedan, registran una mejor satisfacción laboral.
- En los grupos 1 y 2 quienes abandonan registran menor años de trabajo contra quienes no abandonan.
- En el grupo 3 presenta un promedio mayor de años trabajando
- El grupo 3 tiene un promedio mayor de ingreso mensual

###**6. Análisis de tendencias en el tiempo:**

- ¿Ha habido cambios en la tasa de abandono a lo largo del tiempo?

**Respuesta:** No se encontraron variables con datos de tipo **"date"** para realizar operaciones que solvente la pregunta.

- ¿Existen patrones estacionales en el abandono?

**Respuesta:** No se encontraron variables con datos de tipo **"date"** para realizar operaciones que solvente la pregunta.

###**7. Análisis de valores faltantes:**

- ¿Qué porcentaje de datos falta en cada variable?
"""

# Visualizar el porcentaje de valores faltantes por variable
missing_data <- df %>%
  summarise_all(~sum(is.na(.))/n()*100) %>%
  pivot_longer(everything(), names_to = "variable", values_to = "percentage_missing") %>%
  arrange(desc(percentage_missing))

# Imprimir los resultados
head(missing_data,37)

"""**Respuesta:**

Como podemos observar no se presentan datos faltantes dentro del conjunto de datos del dataset

- ¿Cómo afecta la presencia de valores faltantes al análisis? ¿Qué estrategias se
pueden utilizar para tratarlos?

**Repuestas:**

<br>

**Valores faltantes:** <br>
La presencia de valores faltantes puede tener efectos significativos en el análisis de datos:

- **Sesgo en los resultados:** Si los valores faltantes no se distribuyen aleatoriamente (es decir, si ciertos grupos de empleados tienen más datos faltantes que otros), esto puede sesgar tus conclusiones.

- **Pérdida de poder estadístico:**
Si hay muchas variables con valores faltantes, y se eliminan esas observaciones, podrías terminar trabajando con un subconjunto reducido de los datos, lo que reduce la precisión de los resultados.
<Br>

**Estrategias para manejar los valores faltantes:** <br>
Dependiendo de la cantidad de valores faltantes y las variables afectadas, se pueden emplear diferentes estrategias:
- Eliminación de Filas o Columnas del dataset
- Rellenar los valores faltantes con el promedio, mediana o moda de la variable.
- Utilizar modelos como regresión lineal o árboles de decisión, para predecir los valores faltantes

###**8. Análisis de outliers:**

- ¿Existen valores atípicos en las variables numéricas?

**Cálculo del IQR** <br>
Para cada variable numérica, se calculan los cuartiles (Q1 y Q3) y el rango intercuartil (IQR).

<Br>

**Cómo se realiza la detección de outliers?**

- **valores menores:** *Q1 - 1.5 x IQR*. <br>
- **valores mayores:** *Q3 + 1.5 x IQR*
"""

# Seleccionar todas las variables numéricas, excluyendo 'Attrition'
numeric_vars <- df %>%
  select(where(is.numeric), -Attrition)

# Crear un dataframe para almacenar los resultados
outliers_df <- data.frame(Variable = character(), Outliers_Count = integer())

# Identificar outliers y contar cuántos hay por variable
for (var in names(numeric_vars)) {
  # Calcular los cuartiles y el IQR
  Q1 <- quantile(numeric_vars[[var]], 0.25, na.rm = TRUE)
  Q3 <- quantile(numeric_vars[[var]], 0.75, na.rm = TRUE)
  IQR <- Q3 - Q1

  # Definir los límites para los outliers
  lower_bound <- Q1 - 1.5 * IQR
  upper_bound <- Q3 + 1.5 * IQR

  # Contar cuántos outliers hay
  outliers_count <- sum(numeric_vars[[var]] < lower_bound | numeric_vars[[var]] > upper_bound, na.rm = TRUE)

  # Agregar los resultados al dataframe
  outliers_df <- rbind(outliers_df, data.frame(Variable = var, Outliers_Count = outliers_count))
}

# Mostrar las primeras filas de outliers_df
head(outliers_df, 27)

"""**Gráfica de Cajas para identificar Outliers**"""

numeric_vars <- df %>%
  select(where(is.numeric), -Attrition)%>%
  names()

# Graficar boxplots para cada variable numérica
for (var in numeric_vars) {
  # Crear el gráfico
  p <- ggplot(df, aes_string(y = var)) +
    geom_boxplot(outlier.color = "red", outlier.shape = 19, outlier.size = 2) +  # Valores atípicos en rojo
    labs(title = paste("Boxplot de", var)) +
    theme_minimal() +
    ylab(var)

  # Imprimir el gráfico
  print(p)
}

"""**Respuesta:**
Cómo se puede observar las variables:
- MonthlyIncome
- NumCompaniesWorked
- PerformanceRating
-StockOptionLevel
-TotalWorkingYears
-TrainingTimesLastYear
-YearsAtCompany
-YearsInCurrentRole
-YearsSinceLastPromotion
-YearsWithCurrManager <br>

Contienen outliers en su conjunto de datos.

- ¿Cómo afectan los outliers al análisis? ¿Qué se puede hacer con ellos?

**Afectación:** <br>
Los ou setliers pueden tener un impacto significativo en el análisis de datos, especialmente en medidas estadísticas como la media, la varianza y en modelos predictivos que son sensibles a valores extremos (e.g., regresión lineal).


<Br>

**Que hacer con ellos?**

<Br>

**A. Eliminación de Outliers:**
Esto es particularmente útil si son pocos y están afectando significativamente los resultados.

<Br>

**B. Transformación de Variables:**

En lugar de eliminar los outliers, puedes aplicar transformaciones a las variables (como el logaritmo o raíz cuadrada) para reducir su impacto

<Br>

**C. Imputación de Outliers:**

En ciertos casos, puedes reemplazar los valores atípicos con el percentil 5 o 95 de la distribución, manteniendo las observaciones pero reduciendo su efecto.

<Br>

**D. Análisis robusto:**

Si decides no eliminar o transformar los outliers, puedes optar por modelos robustos que no sean sensibles a los valores extremos, como regresiones robustas o medianas en lugar de medias para los cálculos.
"""